# Optimized Docker Compose configuration for Rust Backend Starter
# Implements security, monitoring, and production-ready features

networks:
  app-network:
    driver: bridge
    internal: false

services:
  postgres:
    image: postgres:16-alpine
    container_name: rust_starter_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-rust_starter_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "256M"
        reservations:
          cpus: "0.1"
          memory: "128M"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rust_starter_app
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-rust_starter_db}
      HOST: 0.0.0.0
      PORT: 8000
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION:-86400}
      RUST_LOG: ${RUST_LOG:-info,tower_http=info}
      APP_ENV: ${APP_ENV:-production}
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "256M"
        reservations:
          cpus: "0.1"
          memory: "128M"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "./rust-backend-starter", "--health-check"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
      disable: true
    security_opt:
      - no-new-privileges:true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres_data:
